export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";

// Generic
export const SET_TRIGGER = "SET_TRIGGER";
export const CLEAR_TRIGGER = "CLEAR_TRIGGER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_EMAIL_VERIFIED = "SET_EMAIL_VERIFIED";
export const CLEAR_EMAIL_VERIFIED = "CLEAR_EMAIL_VERIFIED";
export const CLEAR_IS_REGISTERED = "CLEAR_IS_REGISTERED";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";

// User
export const USER_LOADED = "USER_LOADED";

//Posts
export const SET_POSTS = "SET_POSTS"
export const CLEAR_POSTS = "CLEAR_POSTS"
export const POSTS_ERROR = "POSTS_ERROR"

// Add Post
export const ADD_POST = "ADD_POST";

// Update Post
export const UPDATE_POST = "UPDATE_POST";

// Add Post - Error
export const ADD_POST_ERROR = "ADD_POST_ERROR";
export const CLEAR_ADD_POST_ERROR = "CLEAR_ADD_POST_ERROR";
// Add Post - Loading
export const SET_ADD_POST_LOADING = "SET_ADD_POST_LOADING";
export const CLEAR_ADD_POST_LOADING = "CLEAR_ADD_POST_LOADING";

// LIKE POST
export const LIKE_POST = "LIKE_POST";

// COMMENT
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";

// Current
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";

//Filter
export const FILTER_EXPENSES = "FILTER_EXPENSES";
export const CLEAR_FILTER = "CLEAR_FILTER";

// Alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//Auth - set loading
export const SET_LOADING = "SET_LOADING";
export const CLEAR_LOADING = "CLEAR_LOADING";

// profile
export const SET_LOGGED_USER_PROFILE = "SET_LOGGED_USER_PROFILE";
export const CLEAR_LOGGED_USER_PROFILE = "CLEAR_LOGGED_USER_PROFILE";
export const SET_OTHER_USER_PROFILE = "SET_OTHER_USER_PROFILE";
export const CLEAR_OTHER_USER_PROFILE = "CLEAR_OTHER_USER_PROFILE";

export const SET_LOGGED_USER_POSTS = "SET_LOGGED_USER_POSTS";
export const DELETE_LOGGED_USER_POST = "DELETE_LOGGED_USER_POST";
export const CLEAR_LOGGED_USER_POSTS = "CLEAR_LOGGED_USER_POSTS";
export const SET_OTHER_USER_POSTS = "SET_OTHER_USER_POSTS";
export const CLEAR_OTHER_USER_POSTS = "CLEAR_OTHER_USER_POSTS";

export const LOGGED_USER_LIKE_POST = "LOGGED_USER_LIKE_POST";
export const LOGGED_USER_ADD_COMMENT = "LOGGED_USER_ADD_COMMENT";
export const LOGGED_USER_REMOVE_COMMENT = "LOGGED_USER_REMOVE_COMMENT";

export const OTHER_USER_LIKE_POST = "OTHER_USER_LIKE_POST";
export const OTHER_USER_ADD_COMMENT = "OTHER_USER_ADD_COMMENT";
export const OTHER_USER_REMOVE_COMMENT = "OTHER_USER_REMOVE_COMMENT";

export const SET_LOGGED_USER_FRIENDS = "SET_LOGGED_USER_FRIENDS";
export const CLEAR_LOGGED_USER_FRIENDS = "CLEAR_LOGGED_USER_FRIENDS";
export const SET_OTHER_USER_FRIENDS = "SET_OTHER_USER_FRIENDS";
export const CLEAR_OTHER_USER_FRIENDS = "CLEAR_OTHER_USER_FRIENDS";

//Profile - Post - admin
export const DISABLE_OTHER_USER_POST = "DISABLE_USER_POST";
export const ENABLE_OTHER_USER_POST = "ENABLE_USER_POST";
export const DELETE_OTHER_USER_POST = "DELETE_USER_POST";

// profile - error
export const SET_PROFILE_ERROR = "SET_PROFILE_ERROR";
export const CLEAR_PROFILE_ERROR = "CLEAR_PROFILE_ERROR";
// profile - loading
export const SET_PROFILE_LOADING = "SET_PROFILE_LOADING";
export const CLEAR_PROFILE_LOADING = "CLEAR_PROFILE_LOADING";
// profile - friend/friend request
export const ADD_FRIEND = "ADD_FRIEND";
export const SET_SENT_REQUESTS = "SET_SENT_REQUESTS";
export const CLEAR_SENT_REQUESTS = "CLEAR_SENT_REQUESTS";
export const WITHDRAW_FRIEND_REQUEST = "WITHDRAW_FRIEND_REQUEST"
export const SET_PENDING_FRIEND_REQUESTS = "SET_PENDING_FRIEND_REQUESTS"
export const CLEAR_PENDING_FRIEND_REQUESTS = "CLEAR_PENDING_FRIEND_REQUESTS"
export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
export const DECLINE_FRIEND_REQUEST = "DECLINE_FRIEND_REQUEST";
export const REMOVE_FRIEND = "REMOVE_FRIEND";

// Profile - clear all
export const CLEAR_ALL_PROFILE = "CLEAR_ALL_PROFILE";


// Search
export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT"
export const CLEAR_SEARCH_RESULT = "CLEAR_SEARCH_RESULT"

// Admin
export const SET_DASHBOARD_TAB_TYPE = "DASHBOARD_TAB_TYPE";
export const CLEAR_DASHBOARD_TAB_TYPE = "DASHBOARD_TAB_TYPE";
export const SET_USERS = "SET_USERS";
export const CLEAR_USERS = "CLEAR_USERS";
export const SET_FILTERED_USERS = "SET_FILTERED_USERS";
export const CLEAR_FILTERED_USERS = "CLEAR_FILTERED_USERS";
export const SET_ADMIN_ERROR = "SET_ADMIN_ERROR"
export const CLEAR_ADMIN_ERROR = "CLEAR_ADMIN_ERROR"
export const ENABLE_USER = "ENABLE_USER"
export const DISABLE_USER = "DISABLE_USER"
export const DELETE_USER = "DELETE_USER"





